name: 'Publish Python Package'
description: 'Build and publish a Python package to PyPI or Test PyPI'

inputs:
  python-version:
    default: '3.x'
  repository-url:
    default: 'https://upload.pypi.org/legacy/'
  twine-username:
    default: '__token__'
  twine-password:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - run: |
        python -m pip install --upgrade pip
        pip install build twine
      shell: bash

    - run: python -m build
      shell: bash

    - run: |
        twine upload --repository-url ${{ inputs.repository-url }} dist/*
      env:
        TWINE_USERNAME: ${{ inputs.twine-username }}
        TWINE_PASSWORD: ${{ inputs.twine-password }}
      shell: bash
