name: Deploy MkDocs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows:
      - Validate Contributions
    types:
      - completed

jobs:

  deploy:
      if: false # Désactive le workflow
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Deploy
        run: |
          export PYTHONPATH=$(pwd)/contrib:$PYTHONPATH
          mkdocs build
          mkdocs gh-deploy --force
