name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate contribution documentation
        run: python scripts/generate_contrib_docs.py

      - name: Build and Deploy
        run: |
          export PYTHONPATH=$(pwd)/contrib:$PYTHONPATH
          mkdocs build
          mkdocs gh-deploy --force
