name: Test and Lint on contrib

on:
  push:
    paths:
      - 'contrib/**'
  pull_request:
    paths:
      - 'contrib/**'


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.get-changes.outputs.folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed folders
        id: get-changes
        run: |
          echo "Detecting changed folders..."
          CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^contrib/' | cut -d'/' -f2 | sort | uniq)
          echo "Changed folders: $CHANGED_FOLDERS"
          echo "::set-output name=folders::[$(echo $CHANGED_FOLDERS | jq -R -s -c 'split("\n") | map(select(. != ""))')]"
#        run: |
#          echo "::set-output name=folders::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^contrib/' | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')"

  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-changes.outputs.folders) }}
    needs: detect-changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pylint pytest

      - name: Run pylint
        run: |
          pylint contrib/${{ matrix.folder }} > contrib/${{ matrix.folder }}/pylint-report.txt || true

      - name: Run pytest
        run: |
          pytest contrib/${{ matrix.folder }} --junitxml=contrib/${{ matrix.folder }}/pytest-report.xml || true
