name: Validate Contributions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_contribs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml  # Install YAML parser for Python
      
      - name: Run contribution validation
        run: |
          python validate_contributions.py